services:
  frontend:
    container_name: frontend
    image: ives_ilyass_twitter/front
    build:
      context: frontend
      dockerfile: Dockerfile 
    ports:
      - "4200:4200"

  backend:
    container_name: backend
    image: ives_ilyass_twitter/api
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"