apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ives_ilyass_twitter/front
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
          - containerPort: 4200
        
