apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: myTwitter
  template:
    metadata:
      labels:
        app: myTwitter
        type: backend
    spec:
      containers:
      - name: backend
        image: ives_ilyass_twitter/api 
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        ports:
          - containerPort: 5000
        
