apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytwitter-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: myTwitter
  template:
    metadata:
      labels:
        app: myTwitter
    spec:
      containers:
      - name: frontend
        image: ives_ilyass_twitter/front
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
          - containerPort: 4200
      - name: backend
        image: ives_ilyass_twitter/api 
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        ports:
          - containerPort: 5000
      - name: redis
        image: redis
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
          - containerPort: 6379
        
