apiVersion: v1
kind: Service
metadata:
  name: service-redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30003
    protocol: TCP
