apiVersion: v1
kind: Service
metadata:
  name: service-frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 8000
    targetPort: 4200
    nodePort: 30001
    protocol: TCP

